### ISSUE TITLE
Feature request: Expose access to `SetOutput` and maybe `Usage`

### ISSUE THREAD

**Issue by zxchris** [ian-kent/gofigure#7]
It would be *useful* to be able to access `Usage` and `SetOutput` in particular, so any logs/usage dumpage can get emitted by structured logging instead of the default Stdout/err.

I thought that the following would work in the app:

```golang
 // Capture flag output 
 buf := new(bytes.Buffer)
 flag.CommandLine.SetOutput(buf)

 err := gofigure.Gofigure(cfg)

 // We may have output to spew:
 if buf.Len() > 0 {
     log.Error(fmt.Errorf(buf.String()))
 }
```

but alas.... no :-(

Either the execution order is not what I expect, or `flag.CommandLine` is being reset (though I thought I had 'cured' that (see issue on "test flags not working"). Maybe something else!

**Comment by ian-kent** [comment]
So, this isn't a gofigure issue 😄 

If you try the same example with just the core flag package, it doesn't work either...

By default, the `flag.CommandLine` var has `ExitOnError` set, which calls `os.Exit(2)` before your app has a chance to do anything. You'd need to redefine it to set `ContinueOnError` instead:

`flag.CommandLine = flag.NewFlagSet(os.Args[0], flag.ContinueOnError)`

and then call `SetOutput` on that one instead

For it to work properly, you also need to set `flag.CommandLine.Usage`, since I think that defaults to always writing to `os.Stderr` instead of respecting the value passed to `SetOutput`
